[package]
name = "htmlwalk"
version = "0.1.1"
authors = ["alexx <notice-dev@alexx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever  = "0.25"
markup5ever_rcdom = "0.1"
chrono = "0.4" # crate::log::log
